android.useAndroidX=true
android.enableJetifier=true
kotlin.code.style=official
android.builtInKotlin=false
android.newDsl=false
org.jetbrains.compose.experimental.jpro.enabled=false

# JVM memory settings
org.gradle.jvmargs=-Xmx4G -XX:MaxMetaspaceSize=1G -Dfile.encoding=UTF-8 -Dkotlin.daemon.jvm.options="-Xmx2G"
org.gradle.parallel=true
org.gradle.caching=true